package comparsionOperator
import com.itheima.drools.entity.ComparsionOperatorEntity

//测试比较符 contains

rule "rule_comparison_contains"
 when
        ComparsionOperatorEntity(names contains "张三")
        ComparsionOperatorEntity(list contains names)
 then
    System.out.println("规则，rule_comparison_contains触发了。。。");
end

//测试比较符 not contains

rule "rule_comparison_not_contains"
 when
        ComparsionOperatorEntity(names not contains "张三")
        ComparsionOperatorEntity(list not contains names)
 then
    System.out.println("规则，rule_comparison_not_contains触发了。。。");
end

//测试比较符 memberOf

rule "rule_comparison_memberOf"
 when
        ComparsionOperatorEntity(names memberOf list)
 then
    System.out.println("规则，rule_comparison_memberOf触发了。。。");
end

//测试比较符 not memberOf

rule "rule_comparison_not_memberOf"
 when
        ComparsionOperatorEntity(names not memberOf list)
 then
    System.out.println("规则，rule_comparison_not_memberOf触发了。。。");
end

//测试比较符 matches

rule "rule_comparison_matches"
 when
        ComparsionOperatorEntity(names matches "李.*")
 then
    System.out.println("规则，rule_comparison_matches触发了。。。");
end

//测试比较符not matches

rule "rule_comparison_not_matches"
 when
        ComparsionOperatorEntity(names not matches "王.*")
 then
    System.out.println("规则，rule_comparison_not_matches触发了。。。");
end